---
- hosts: node17
  connection: local
  become: true
  gather_facts: no

  tasks:
    - name: link network boot image
      file:
        src: /share/tftpboot/images/{{ serial }}
        dest: /share/tftpboot/{{ serial }}
        state: link
    - name: clear local ssh key store
      command: ssh-keygen -f ~/.ssh/known_hosts -R {{ inventory_hostname }}
      failed_when: no
    - name: reboot
      reboot:
        reboot_timeout: 0
      delegate_to: "{{ inventory_hostname }}"

