# $ sshpass -p password ansible-playbook -i hosts -e @parameters.yml setup_computes.yml --ask-pass
---
- hosts: compute
  remote_user: ansible
  become: true
  gather_facts: no
  roles:
    - hostname
    - nfs-client
    - mpienv
  tasks:
    - name: install common packages
      apt:
        update_cache: yes
        name:
          - make
          - python3-pip
    - name: set timezone
      timezone:
        name: Asia/Tokyo

- hosts: node10
  remote_user: ansible
  become: true
  gather_facts: no
  roles:
    - jupyter

- hosts: mng
  connection: local
  become: true
  gather_facts: no
  tasks:
    - name: prerouting for jupyter
      iptables:
        table: nat
        chain: PREROUTING
        protocol: tcp
        destination_port: "18888"
        jump: DNAT
        to_destination: 192.168.2.10:8888
      notify: save iptables
  handlers:
    - name: save iptables
      command: netfilter-persistent save
