---
- name: install mosquitto
  apt:
    name:
      - mosquitto
      - mosquitto-clients
- name: restart mosquitto
  systemd:
    name: mosquitto.service
    state: restarted
    daemon_reload: yes
    enabled: yes
